[tool.poetry]
name = "homework-05"
version = "0.1.0"
description = ""
authors = ["PristenCityMan <timonovsv1@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
